### ISSUE TITLE
%spigotpapi_parse_[placeholder]% crashing server

### ISSUE THREAD

**Issue by griffindeed** [EnvyWare/ForgePlaceholderAPI#2]
Was testing placeholders to use in ForgeMenus via holograms, %forge_name% worked then I tried %spigotpapi_parse_jobsr_user_points% and it crashed the server. Not sure if I'm misusing or if it's an issue with the mod. Attached crash report:
[crash-2022-06-18_00.14.10-server.txt](https://github.com/EnvyWare/ForgePlaceholderAPI/files/8931871/crash-2022-06-18_00.14.10-server.txt)

**Comment by austin4195** [comment]
This is a known issue with Arclight 1.16.5. Not much can be done about it...

You can use Forge Placeholders in things like DeluxeMenus, TAB, and other Spigot plugins however you cannot use Spigot placeholders in things like ForgeMenus, ForgeTAB, etc.
